//this file is used to put dynaminc values for backend foe dev env
bucket         = "hr-terraform-state-demo-12345"
key            = "devops/dev/terraform.tfstate"
region         = "ap-south-1"
dynamodb_table = "terraform-locks"
encrypt = true

///we have to give terraform -init -backend-config =dev.conf so that i takes dymainc backned from dev.conf